services:
    app.goalapi_listener.load:
        class: App\AppBundle\EventDispatcher\EventListener\DataLoadListener
        tags:
            - { name: kernel.event_listener, event: goalapi.load, method: onDataLoad }
        calls:
        - ['setDataPath', ['%goalapi.opendata.datapath%']]

    App\AppBundle\Command\DumpCommand:
        tags: [console.command]
        calls:
        - ['setSdk', ['@goalapi.sdk']]
