imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

parameters:
    locale: en
    goalapi.opendata.datapath: '%kernel.project_dir%/var/data'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    default_locale:  "%locale%"

goalapi:
    apikey: '%goalapi.apikey%'

monolog:
    handlers:
        error:
            type:   stream
            path:   "%kernel.logs_dir%/error.%kernel.environment%.log"
            level:  error
            bubble: false
        warning:
            type:   stream
            path:   "%kernel.logs_dir%/warning.%kernel.environment%.log"
            level:  warning
            bubble: false
        console:
            type:  console
